### PR TITLE
Fixes #2 Serving JSX with Python

### LINKED ISSUE #2: Making getComponent.js More Simple
I think Remote Components `getComponent.js` should be as simple as any other React Native.

@clayallsopp What do you think?

### PR DESCRIPTION
**Pull request by iraycd**

### CODE REVIEW

**Comment by iraycd** [comment]
This fixes #2

**Comment by hellogerard** [comment]
@iraycd Really interesting PR here (I think it should be merged 😄 ). The new `getComponent.jsx` looks like any other React Native component. Do you foresee any limitations here? Could the remote component be a full mobile screen? What about transitioning between two remote components?

**Comment by vvavepacket** [comment]
@iraycd  is python required? i didnt use any python and just copied your remotecomponent and getcomponent,, below is my getComponent.jsx (exactly the same except i added some logging capability/console.log)

```
(function main(React, ReactNative, require) {

  var StyleSheet = ReactNative.StyleSheet;
  var View = ReactNative.View;
  var Text = ReactNative.Text;
  var LayoutAnimation = ReactNative.LayoutAnimation;

  const styles = StyleSheet.create({
        textColor: {
          color: "#F00"
        }
  }); 

  class Test extends React.Component {
componentWillMount() {
console.log('mounting')
}
componentDidMount() {
console.log('mounted')
}
    render(){
      return (
          <View style={{flex:1, flexDirection:'column', alignItems:'center', alignSelf:'center'}}>
            <Text style={styles.textColor}> Hello from {this.props.url}</Text>
          </View>
      );
    }
  }

  return Test
});
```

I got the following error:

[https://i.snag.gy/s9CMhG.jpg](url)

It says that there is an error in '<' (which I assume it doesn't recognize JSX syntax). How do we make the remote components working with JSX? Thank you.

**Comment by iraycd** [comment]
Python is required.

**Pull request closed without merging**
